require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  Exclude:
    - 'db/migrate/*.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
