name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Run RSpec
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RACK_ENV: test
        run: bundle exec rspec

      - name: Run RuboCop
        run: bundle exec rubocop

